# Generated by Django 4.1.3 on 2022-12-04 18:33

from django.db import migrations, models
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=500)),
                ('customer_username', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('customer_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('customer_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['customer_created'],
            },
        ),
    ]
