# Generated by Django 4.1.3 on 2022-12-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customer_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_user',
            new_name='user',
        ),
    ]
