# Generated by Django 4.1.3 on 2022-12-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customer_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_location',
        ),
    ]
