# Generated by Django 4.1.3 on 2022-12-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_rename_customer_name_customer_customer_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_fname',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_lname',
        ),
    ]
