# Generated by Django 4.1.3 on 2022-12-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_rename_customer_fname_customer_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='customer_fname',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_lname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
