# Generated by Django 4.1.3 on 2022-12-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_rename_customer_name_customer_customer_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_fname',
            new_name='customer_first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_lname',
            new_name='customer_last_name',
        ),
    ]
