# Generated by Django 4.1.3 on 2022-12-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privileges',
            name='privileges_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
