# Generated by Django 4.1.3 on 2022-12-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_privileges_privileges_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_name', '-employee_created']},
        ),
        migrations.AlterField(
            model_name='privileges',
            name='privileges_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
