# Generated by Django 4.1.3 on 2022-12-07 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('maintenance', '0003_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.category'),
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_customer_id',
        ),
        migrations.AddField(
            model_name='request',
            name='request_customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.customer'),
        ),
    ]
