# Generated by Django 4.1.3 on 2022-12-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_customer_customer_image'),
        ('maintenance', '0005_alter_request_request_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.category'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.customer'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.employee'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.location'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_sub_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.sub_category'),
        ),
    ]
