# Generated by Django 4.1.3 on 2022-12-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_alter_request_options_remove_request_request_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_employee_id',
        ),
        migrations.AddField(
            model_name='request',
            name='request_employee_id',
            field=models.ManyToManyField(blank=True, null=True, to='maintenance.employee'),
        ),
    ]
