# Generated by Django 4.1.3 on 2022-12-13 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_remove_request_request_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_video',
            field=models.FileField(blank=True, null=True, upload_to='requests_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
