# Generated by Django 4.1.3 on 2022-12-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_alter_customer_customer_email_and_more'),
        ('maintenance', '0010_request_request_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['status_state']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_username',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.customer'),
        ),
    ]
