# Generated by Django 4.1.3 on 2022-12-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_alter_employee_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_name',
            new_name='employee_customer_id',
        ),
    ]
