# Generated by Django 4.1.3 on 2022-12-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_rename_employee_name_employee_employee_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_customer_id',
            new_name='employee_customer_user_name',
        ),
    ]
