# Generated by Django 4.1.3 on 2022-12-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_rename_employee_customer_id_employee_employee_customer_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_customer_user_name',
            new_name='employee_user_name',
        ),
    ]
