# Generated by Django 4.1.3 on 2022-12-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_alter_customer_customer_email_and_more'),
        ('maintenance', '0014_rename_employee_customer_user_name_employee_employee_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='call_request',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_user_name', '-employee_created']},
        ),
    ]
