# Generated by Django 4.1.3 on 2022-12-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_rename_request_call_request_alter_employee_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_request',
            name='request_message_id',
        ),
        migrations.AddField(
            model_name='call_request',
            name='request_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
