# Generated by Django 4.1.5 on 2023-01-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_remove_call_request_request_message_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_id', '-employee_created']},
        ),
        migrations.RemoveField(
            model_name='call_request',
            name='request_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='status_request',
            name='status_request_request_id',
        ),
        migrations.AddField(
            model_name='call_request',
            name='request_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.status'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.call_request'),
        ),
        migrations.AlterField(
            model_name='call_request',
            name='request_img',
            field=models.ImageField(blank=True, default='/user.png', null=True, upload_to='requests_images'),
        ),
    ]
